### PR TITLE
New block: Theme settings for owners to control community/commercial URLs

### LINKED ISSUE #34: Block: Community options (owners only)
This is a set of options only available to owners and admins.

Image

### LINKED ISSUE #35: Block: Commercial options (owners only)
This is a set of options only available to owners and admins.

Image

### PR DESCRIPTION
**Pull request by ryelle**
This creates a single new block for theme owners to configure settings related to their theme. Currently the only option is the URL for either support (commercial themes) or a development repo (community themes).

Fixes #34, fixes #35 

### Screenshots

Before

| Community | Commercial |
|---|---|
| Image | Image |

After

| Community | Commercial | Neither |
|--------|-------|---|
| theme-community | theme-commercial | theme-none |

When saving, the form submits to the API and adds a message next to the button. This message is also announced to screen readers. It does not automatically update the URL at the top of the page, if this is confusing we could possibly add a note to reload the page?

| Success | Error |
|--------|-------|
| Screenshot 2024-05-15 at 5 50 55 PM | Screenshot 2024-05-15 at 5 51 26 PM |

### How to test the changes in this Pull Request:

1. View a community theme either as the theme owner or a side admin/moderator
2. You should see the "Theme options" section
3. Update the field
4. It should only accept URLs (browser input validation)
5. Reloading the page, the "Contribute to this theme" link should use the new URL
6. Repeat testing on a commercial theme

### CODE REVIEW

**Comment by jasmussen** [comment]
Vast improvement.

More of a site-wide-styles question, so not a blocker for this PR, but some of the componentry here could be improved:

Screenshot 2024-05-16 at 09 40 24

* Default button size should match [this](https://www.figma.com/design/HOJTpCFfa3tR0EccUlu0CM/WordPress.org-Design-Library?node-id=2710%3A958&t=lsiKq134TI5lhMpj-1). It might already, but it looks a bit smaller. 
* Inputs and textareas should match [these](https://www.figma.com/design/HOJTpCFfa3tR0EccUlu0CM/WordPress.org-Design-Library?node-id=2419%3A7707&t=lsiKq134TI5lhMpj-1), both in size, padding, and charcoal border color. Current gray border looks on the light side, maybe below 3:1 contrast.

We were also missing an example for how to best structure label+input+help text, as far as font sizes, gap, paddings, colors. So I quickly extracted one from the recent Learn work, and put it [here](https://www.figma.com/design/HOJTpCFfa3tR0EccUlu0CM/WordPress.org-Design-Library?node-id=5165%3A962&t=lsiKq134TI5lhMpj-1):

Screenshot 2024-05-16 at 09 45 29

So small paragraph charcoal-4 helptext, long paragraph label and input.

**Comment by fcoveram** [comment]
Here is an idea that taps into @jasmussen's

Error and success messages in theme url process

The changes are:
* Replacing the blue callout with default text in "paragraph (long)" style.
* Adding the [Field component](https://www.figma.com/design/HOJTpCFfa3tR0EccUlu0CM/WordPress.org-Design-Library?node-id=5175-3293&m=dev), as per Joen's design.
* Showing the error message in inside the [Callout "warning"](https://www.figma.com/design/HOJTpCFfa3tR0EccUlu0CM/WordPress.org-Design-Library?node-id=1264-4116&m=dev) variant.
* Adding more words in the success sentence to increase its recognition.

I added a new page in the [Themes file](https://www.figma.com/design/DQuNUBmyVbbtJNOqCSrAPH/Themes?node-id=0-1&t=W1Ov3RHQAXcTJD4w-0) where [this section](https://www.figma.com/design/DQuNUBmyVbbtJNOqCSrAPH/Themes?node-id=3919-979&m=dev) has both mockups.What do you think @ryelle?

**Comment by ryelle** [comment]
I don't really want to spend a lot of time on this, so what do you think about leaving the error message where it is in the success position? Right now I use the same element for that, so it would just take more refactoring to put it into the notice and still have it correctly read by screen readers.

(small edit to give context and not just sound lazy 😅  — right now, this section is not used by many people - it's probably only set once by a theme owner, for just a subset of themes, and then left as-is. if we add more fields to this in the future, we can definitely move around the error & make it more helpful)

The rest seems to be just CSS updates, so that's all fine 👍🏻

**Comment by fcoveram** [comment]
That sounds good @ryelle 🚀

**Comment by ryelle** [comment]
Screenshot with the design updates:

Screenshot 2024-05-16 at 10 56 45 AM

**Pull request merged**
