### PR TITLE
Navigation: Add "Log in" link to local nav

### PR DESCRIPTION
**Pull request by ryelle**
This updates the Theme Directory to include the "Sign in" link in the local navigation across the site. The link only appears when you're logged out, once logged in, you can manage your account/login status in the admin bar.

I've already deactivated the "Logged Out Admin Bar" plugin on this site, so it won't show until you log in (and then it will show on all sites, see https://github.com/WordPress/wporg-mu-plugins/commit/3b39f5f1d1134b266e68ac966744a584d464279b).

See https://github.com/WordPress/wporg-mu-plugins/issues/647

### Screenshots

| Logged out | Logged in |
|--------|-------|
| Screen Shot 2024-09-09 at 16 37 30 | Screen Shot 2024-09-09 at 17 17 00 |

### How to test the changes in this Pull Request:

1. Be logged out
2. There should be a "sign in" link
3. Clicking it and signing in should redirect you back to the page you were just on
4. The "sign in" link should not appear
5. You should see the admin bar

### CODE REVIEW

**Review by adamwoodnz — APPROVED** [review]
👍 Works for me

**Comment by jasmussen** [comment]
Apologies for being late on this, can we change it from "Sign in" to "Log in" per [this feedback](https://github.com/WordPress/wporg-mu-plugins/issues/647#issuecomment-2310541536)? 

Other than that, this is fantastic, thanks so much for working on this 🙏

**Comment by ryelle** [comment]
Text updated to "Log in"

Screenshot 2024-09-10 at 10 27 21 AM

**Comment by ndiego** [comment]
> Text updated to "Log in"

Looks great @ryelle ✨

**Review by ndiego — APPROVED** [review]
I can't speak to the code, but the functionality looks good.

**Pull request merged**
